Dev 163 create industry page
tum-ai/website-nextjs pull request #18
Opened 2023-06-26 23:50 UTC by Max-vS

Can still be optimized, but just to get a solid version out there.

2023-06-27 23:07 UTC, simon-hng approved these changes
Very cool! Thank you max

2023-06-27 23:07 UTC, simon-hng commented on pages/industry.tsx
> +      image: "/assets/industry/project_cards/Unbenannt 2.jpg",
The image set as source here does not exist

2023-06-27 23:07 UTC, simon-hng commented on pages/industry.tsx
> +                <span>Options</span>
IMO we can just stick with the tabs here

2023-06-28 09:14 UTC, Max-vS commented on pages/industry.tsx
> +                <span>Options</span>
They rearrange weirdly when screen is shrunk.

2023-06-28 17:21 UTC, simon-hng requested changes
I talked with Mohammed and we decided that we want to resolve the todos before merging

2023-06-28 17:21 UTC, simon-hng commented on pages/industry.tsx
> +import {
- [ ] TODO: refactor to use fontawesome icons

2023-06-28 17:21 UTC, simon-hng commented on pages/industry.tsx
> +import { Dialog, Transition, Popover } from "@headlessui/react";
- [ ] TODO: Refactor to use radix-ui

2023-06-28 17:24 UTC, simon-hng commented on pages/industry.tsx
> +                <span>Options</span>
- [ ] TODO: Replace with [radix-ui tabs](https://www.radix-ui.com/docs/primitives/components/tabs)

2023-06-28 20:45 UTC, simon-hng approved these changes

2023-06-28 21:24 UTC, merged