Dev 168 stat component
tum-ai/website-nextjs pull request #20
Opened 2023-06-28 09:15 UTC by Max-vS

2 different versions of a stat component. Have displayed them in the e-lab page.

![image](https://github.com/tum-ai/website-nextjs/assets/25489463/8d56b7cc-69fc-44ff-a674-3622888e684b)

2023-06-28 10:37 UTC, simon-hng commented on components/01_atoms/Stat2.tsx
> +  const textColorClass = `text-${color}`;
That probably doesn't work

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

2023-06-28 10:37 UTC, simon-hng commented on components/01_atoms/Stat.tsx
> +export default function Stat({ description, value }) {
Why do we need two stat components?

2023-06-28 10:37 UTC, simon-hng commented on components/01_atoms/Stat.tsx
> +export default function Stat({ description, value }) {
We don't use the 01_atoms and molecule folders anymore. just `/components` is fine

2023-06-28 10:37 UTC, simon-hng commented on components/01_atoms/Stat2.tsx
> +    <div className="flex h-28 w-48 max-w-sm flex-col items-center justify-center space-y-1 rounded-xl">
Instead you could just pass `className` as prop and do that
```suggestion
    <div className={cx("flex h-28 w-48 max-w-sm flex-col items-center justify-center space-y-1 rounded-xl", className)}>
```

2023-06-28 19:42 UTC, simon-hng approved these changes

2023-06-28 19:42 UTC, simon-hng commented on components/Stat.tsx
> +import cx from 'classnames';
should be an import from `cva`

2023-06-28 20:49 UTC, simon-hng requested changes
Can you move elab.tsx file into e-lab.tsx since thats where the hero already exists

2023-06-29 14:05 UTC, simon-hng approved these changes

2023-06-29 18:36 UTC, MunzerDw approved these changes
Top, thanks!

2023-06-29 18:37 UTC, merged