Dev 147 create partners page in nextjs
tum-ai/website-nextjs pull request #8
Opened 2023-06-07 18:42 UTC by simon-hng

First implementation of partner page in nextjs.

2023-06-07 18:44 UTC, simon-hng commented on pages/partners.js
> +      img: "https://www.tum-ai.com/assets/img/mainpage_slideshow/alelphalpha_workshop_group.jpg",
Images need to be downloaded and added in assets but I was too lazy to do it yet

2023-06-07 18:45 UTC, simon-hng commented on pages/partners.js
> +          Partners <span className="text-[#5a2de5]">we have collaborated</span>{" "}
We define various shades of purple in `tailwind.config` and yet non of them match the one on the website.

Color usage needs to be documented somewhere

2023-06-07 20:57 UTC, MunzerDw commented
I know you are not done yet, but it looks great so far! Thanks for your work.
I will adapt my branch to yours once we merge this branch.

2023-06-11 19:36 UTC, MunzerDw requested changes
looks great, thanks!
Could you please move the sections into different components?

2023-06-11 19:36 UTC, MunzerDw commented on pages/partners.js
> +              <img src={card.img} />
Please use nextjs Image component :).

2023-06-11 19:36 UTC, MunzerDw commented on pages/partners.js
> +          Partners <span className="text-[#5a2de5]">we have collaborated</span>{" "}
Sure, how about we call the colors "primary", "secondary", "tertiary" etc.? You can already implement that in your branch.

2023-06-11 19:36 UTC, MunzerDw commented on pages/partners.js
> +      img: "https://www.tum-ai.com/assets/img/mainpage_slideshow/alelphalpha_workshop_group.jpg",
hahah no worries

2023-06-11 22:26 UTC, simon-hng commented on pages/partners.js
> +              <img src={card.img} />
outdated - already done

2023-06-11 22:28 UTC, simon-hng commented
I don't think creating components out of the sections here is the right step and we should merge this ASAP. We can still create components out of the sections here in the future when the need arises

2023-06-12 17:08 UTC, MunzerDw approved these changes

2023-06-12 17:08 UTC, merged